trigger:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: music_assistant_alarm

stop:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: music_assistant_alarm

snooze:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: music_assistant_alarm

refresh_media:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: music_assistant_alarm
